name: Build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build web
        run: cd web && bun run build

      # TODO: Enable if vitest dosen't hang anymore
      # - name: Test web
      #   run: cd web && bun run test
